FROM node:14-alpine

ARG NODE_ENV
ARG DB_USERNAME_ARG
ARG DB_PWD_ARG
ARG DB_HOSTNAME_ARG
ARG SUPER_ADMIN_PWD_ARG
ARG SUPER_ADMIN_USERNAME_ARG
ARG JWT_SECRET_ARG
ARG TOKEN_EXPIRY_ARG

WORKDIR /usr/app

COPY package*.json ./

ENV PORT=8080
ENV NODE_ENV=$NODE_ENV
ENV DB_USERNAME=$DB_USERNAME_ARG
ENV DB_PWD=$DB_PWD_ARG
ENV DB_HOSTNAME=$DB_HOSTNAME_ARG
ENV SUPER_ADMIN_PWD=$SUPER_ADMIN_PWD_ARG
ENV SUPER_ADMIN_USERNAME=$SUPER_ADMIN_USERNAME_ARG
ENV JWT_SECRET=$JWT_SECRET_ARG
ENV TOKEN_EXPIRY=$TOKEN_EXPIRY_ARG

RUN npm install

COPY . .

CMD ["npm", "run", "start"]
