version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile-development
        command: sh -c 'while ! nc -z postgres 5432; do sleep 1; echo waiting...; done; npm run start:dev'
        volumes:
            - .:/usr/app/
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        env_file: .env
    postgres:
        image: postgres:12.6-alpine
        ports:
            - "5432:5432"
        container_name: postgres-et
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: etdb
            POSTGRES_PASSWORD: postgres
